language: java
sudo: false
addons:
  apt:
    packages:
    - firefox
    - httpie
    - jq
env:
  global:
  - WEB_SERVER=http://localhost:5516
  - BROWSER=firefox
  - secure: pIKhZJtWf+UlvWZGkdB7TIlo0hWiivGSdCQQRpATutgMchkaIwQCnbfndc7gAzy4+jxyOlHnl8fnfpIBQE4cc78KFGB2m07AVcLwotl7ovttDm4OQr/fk/y7XX69exsWh+3kxKM+qmeYIt2SA419/rKD8Ib1Zn7IZ+x9dPKL7tU=
  - secure: FU6UQMUkfzPcfTZP7Cmq8Qi90q9e8aETKzej1IomNhagvM4T7ii9AWgD9ZM79bQiEYpIZgouUNUdImUc4u5uaOsACP3Kzyc3VshGY1T9oZm4ZDShHEyM4ywg27oDoGVfJcLv47xmUmTC7gObg6kgFCb3rKXOgq2DC1QtnDoLKwM=
script:
- "curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep \"browser_download_url.*linux64.tar.gz\" | cut -d: -f 2,3 | tr -d \\\" | wget -qi -"
- mkdir geckodriver
- tar -xzf *linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver
- mkdir -p ./xl-licenses
- http --check-status --print=b --auth $username:$password --json POST https://download.xebialabs.com/api/temporary/xl-release
  firstName=xlc lastName=xlc email=xlc@xebialabs.com company=xebialabs | jq --raw-output
  '.license' > ./xl-licenses/xl-release-license.lic
- "./gradlew clean assemble"
- docker run --rm -d -v $PWD/build/libs/.:/opt/xlr/server/plugins/__local__ -v $PWD/xl-licenses:/license
  -p 5516:5516 --name xlr xebialabs/xl-release:8.6.2
- sleep 60
- docker logs xlr
- "./gradlew itest"
- docker stop xlr
notifications:
  slack:
    secure: SlqCs/W3tzwLp96aL9yyKr6k0j02CGbAgY3iaO6J5Ba4xM0FCI/r1jncbFGLGDtvhN9EvAY/WWT34k0HR9iIwmTlXXiEdUuzT7yv8NutHuGY00wUdcin6GQkCqZqj9Jou+IJavGrJIUkM18gGPrWIva2SSMY9X9J51CqbKitRM8=
deploy:
  provider: releases
  api_key:
    secure: j3BjPlBnM9J1bMBN2SVxieOvT8fiwk+O737fE311y9aNg3EFoUWeMsh88sp/MAQZ/E4H1WH7LnA+zRWGx3Wl0dPw3t4nqec/2gQmWHX4aGPNXZMumcDzaQQiRp0d+kr3I3qeqps6c0XV465UUu6ND6m35rKQmXhIJlROfCdnN0E=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-servicenow-plugin
